cors:
    origin-alloweds-pattern: "http://localhost:4200/**"
file:
    upload-dir: /Users/gugag/Projetos/uploadDir
security:
    jwt:
        token:
            secret-key: "${ SECRET-KEY: 53cr37 }" #Definindo a leitura de uma variável de ambiente
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sistema_medico
        username: postgres
        password: 704980
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: false
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
